field.widget.third_party.conditional_fields:
  type: sequence
  label: 'Conditions'
  sequence:
    type: mapping
    label: 'Conditional field data'
    mapping:
      uuid:
        type: string
      entity_type:
        type: string
        label: 'Entity type id'
      bundle:
        type: string
        label: 'Bundle id'
      dependee:
        type: string
        label: 'Dependee field name'
      settings:
        type: conditional_fields.settings
        label: 'Condition settings'

# TODO: Check all points.
conditional_fields.settings:
  type: mapping
  label: 'Condition settings'
  mapping:
    state:
      type: string
    condition:
      type: string
    grouping:
      type: string
    values_set:
      type: integer
    value:
      type: string
    values:
      type: sequence
      sequence:
        type: string
    value_form:
      type: sequence
      sequence:
        type: string
    effect:
      type: string
    effect_options:
      type: sequence
    element_view: # Not sure
      type: sequence
      sequence:
        type: string
    element_view_per_role:
      type: boolean
    element_view_roles:
      type: sequence
      sequence:
        type: string
    element_edit: # Not sure
      type: sequence
      sequence:
        type: string
    element_edit_per_role:
      type: boolean
    element_edit_roles:
      type: sequence
      sequence:
        type: string
    selector:
      type: string
